### ISSUE TITLE
joda-time:joda-time - J2ObjC continuous build

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-common-libs-e2e-test#14]
Quality replacement for the Java date and time classes.

@jodastephen, @broneill - FYI for you both. This is to support translation of your Java library to Objective-C such that it can be used on iOS. This bug is specifically for testing this as part of a continuous build using Google's J2ObjC conversion tool.

@advayDev1 FYI

**Comment by advayDev1** [comment]
Depends on and is blocked by #25

**Comment by broneill** [comment]
I've not been involved in the Joda project for many years now. The new time package in Java 8 is better than Joda-Time, and I think you should model it instead. I think Stephen would agree with you.

**Comment by advayDev1** [comment]
Thanks @broneill ; it is the case that some of our users still use Java 7, so we still have demand for Joda-Time.

**Comment by brunobowden** [comment]
Java 8 isn't supported on Android yet. Even when that happens, many
developers will still need to develop for older Android devices stuck on
Java 7. So this'll be useful for some time to come.
