### ISSUE TITLE
joda-time & joda-convert - can't build due to missing Guava dependencies

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-common-libs-e2e-test#40]
@advayDev1 - is it possible to build with the guava dependency? J2ObjC gradle builds include that automatically (many libs use that)... but j2objcTranslation does not?

**Comment by advayDev1** [comment]
I need some more info.  Logs, versions, etc.?

**Comment by advayDev1** [comment]
Answered my own question:
https://travis-ci.org/j2objc-contrib/j2objc-common-libs-e2e-test/jobs/82873499

Yeah should be simple...

**Comment by advayDev1** [comment]
Btw, this has nothing to do with j2objcTranslation.  I hadn't included guava as a normal 'compile' dependency (for Java) for this Joda libraries, because their pom said the dependency was optional.  Either way fixed now in PR #41
