### ISSUE TITLE
com.facebook.stetho:stetho - J2ObjC continuous build

### ISSUE THREAD

**Issue by brunobowden** [j2objc-contrib/j2objc-common-libs-e2e-test#8]
Debug bridge for Android applications, using the powerful Chrome Developer Tools.

@jasta, @rickbrew - FYI for you both. This is to support translation of the Java library to Objective-C using J2ObjC such that it can be used on iOS. This bug is specifically for testing this as part of a continuous build.

@advayDev1 FYI

**Comment by jasta** [comment]
Err, how is that going to work? :)  Stetho uses a fair bit of Android internals, not the least of which being the LocalSocket concept which is, AFAIK, unique to Linux and doesn't even exist on OS X.

**Comment by brunobowden** [comment]
@jasta - I'm inclined to agree with you. J2ObjC does support a limited number of android classes [see docs](http://j2objc.org/reference/packages.html) but it falls far short of what I can see being used in stetho. Let's ice this issue for now and we may return to it later on. You can see a current list of libraries that we're translating from the latest build:

https://travis-ci.org/j2objc-contrib/j2objc-common-libs-e2e-test
